### ISSUE TITLE
GitHub Actions - deprecated warnings found - Jira Sync

### ISSUE THREAD

**Issue by sarahethompson** [hashicorp/hcdiag#323] opened 2023-05-16 00:08 UTC
Workflow Name: Jira Sync
Branch: main
Run URL: https://github.com/hashicorp/hcdiag/actions/runs/4058691574

save-state deprecation warnings: 0
set-output deprecation warnings: 1
node12 deprecation warnings: 1

Please review these deprecation warnings as soon as possible and merge in the necessary updates.

GitHub will be removing support for these commands and plan to fully disable them on 31st May 2023. At this time, any workflow that still utilizes these commands will fail. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

GitHub have not finalized a date for deprecating node12 yet but have indicated that this will be summer 2023. So it is advised to switch to node16 asap. See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

If you need any help, please reach out to us in #team-rel-eng.

**Comment by nwchandler** [comment] 2023-05-16 15:52
Node warnings were resolved by https://github.com/hashicorp/hcdiag/pull/318 .

Run with node warnings fixed: https://github.com/hashicorp/hcdiag/actions/runs/4994042437

**Comment by nwchandler** [comment] 2023-05-16 16:17
This should be resolved in #324 but I don't think I can confirm that until it is merged. I'll close this issue once I've confirmed, along with a clean run link.

**Comment by nwchandler** [comment] 2023-05-16 17:39
#324 is merged. I'm commenting here to run the Jira workflow.

**Comment by nwchandler** [comment] 2023-05-16 17:41
OK, looks like a clean run for the Jira workflow: https://github.com/hashicorp/hcdiag/actions/runs/4995035984

**Closed by nwchandler** 2023-05-16 17:41 UTC
