### ISSUE TITLE
Vault capture with invalid token results in unexpected error message

### ISSUE THREAD

**Issue by davemay99** [hashicorp/hcdiag#81] opened 2022-03-04 23:50 UTC
When capturing from a Vault server using an invalid token, a permission denied error results in the confusing error message `json.Unmarshal error: invalid character 'E' looking for beginning of value"`.

Vault environment variables:
```
$ env | grep VAULT
VAULT_ADDR=http://192.168.1.64:8200
VAULT_TOKEN=invalid
```

hcdiag output:
```
$ ./hcdiag -vault
2022-03-04T18:45:16.027-0500 [INFO]  hcdiag: Checking product availability
2022-03-04T18:45:16.499-0500 [INFO]  hcdiag: Gathering diagnostics
2022-03-04T18:45:16.499-0500 [INFO]  hcdiag: Running seekers for: product=host
2022-03-04T18:45:16.499-0500 [INFO]  hcdiag: running: seeker=stats
2022-03-04T18:45:16.499-0500 [INFO]  hcdiag: Running seekers for: product=vault
2022-03-04T18:45:16.499-0500 [INFO]  hcdiag: running: seeker="vault version"
2022-03-04T18:45:16.559-0500 [INFO]  hcdiag: running: seeker="vault status -format=json"
2022-03-04T18:45:16.628-0500 [INFO]  hcdiag: running: seeker="vault read sys/health -format=json"
2022-03-04T18:45:16.693-0500 [INFO]  hcdiag: running: seeker="vault read sys/seal-status -format=json"
2022-03-04T18:45:16.759-0500 [INFO]  hcdiag: running: seeker="vault read sys/host-info -format=json"
2022-03-04T18:45:16.830-0500 [WARN]  hcdiag: result: seeker="vault read sys/host-info -format=json" result=%!s(<nil>) error="json.Unmarshal error: invalid character 'E' looking for beginning of value"
2022-03-04T18:45:16.830-0500 [INFO]  hcdiag: running: seeker="vault debug -output=hcdiag-2022-03-04T234516Z/VaultDebug.tar.gz -duration=10s"
2022-03-04T18:45:27.914-0500 [INFO]  hcdiag: Created Results.json file: dest=hcdiag-2022-03-04T234516Z/Results.json
2022-03-04T18:45:27.915-0500 [INFO]  hcdiag: Created Manifest.json file: dest=hcdiag-2022-03-04T234516Z/Manifest.json
2022-03-04T18:45:27.918-0500 [INFO]  hcdiag: Compressed and archived output file: dest=hcdiag-2022-03-04T234516Z.tar.gz
```

vault CLI output:
```
$ vault read sys/host-info -format=json
Error reading sys/host-info: Error making API request.

URL: GET http://192.168.1.64:8200/v1/sys/host-info?-format=json
Code: 403. Errors:

* permission denied
```

**Comment by nwchandler** [comment] 2022-04-18 18:17
### Summary

I think this is a bit better behaved in `main`, although not yet released. In `main`, the output in such a condition is:

```
2022-04-11T17:08:21.919-0400 [WARN]  hcdiag: result: seeker="vault read sys/host-info -format=json"
  result=
  | Error reading sys/host-info: Error making API request.
  | 
  | URL: GET http://127.0.0.1:8200/v1/sys/host-info?-format=json
  | Code: 403. Errors:
  | 
  | * permission denied
   error="exec.Command error: exit status 2"

```

Would this be acceptable, @davemay99 ?

### The longer story / root cause

The bad error message was due to a code path where we would catch an error, but rather than returning it right away, we still attempted to unmarshal the error message as json. See [line 33 here](https://github.com/hashicorp/hcdiag/blob/v0.2.0/seeker/commander.go#L32-L34), where we assign to `err` but do not return.

Unfortunately, the CLI output (`Error reading sys/host-info: Error making API request ...`) is not JSON. So, it failed on the very first character, `E`, since it was not able to unmarshal.

While making some other changes to our internal status reporting approach, this behavior was changed so that an error condition immediately returns, bypassing the attempt to unmarshal. See the [changes in this commit](https://github.com/hashicorp/hcdiag/commit/7e0dcc7a9c18e6056234afd9bc5004262bb14b2e#diff-a7b8bf0fa4c55f5ccf153ef8764d357e85c45f05f8fd8bdbba6f833225788e67R37-R40) for how this was changed.

**Comment by aliciaclark1066** [comment] 2022-07-21 21:17
Hi Dave, this issue has been resolved in v.0.3.1. Thanks for reporting!

**Closed by aliciaclark1066** 2022-07-21 21:17 UTC
